# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thing/thing.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11thing/thing.proto\x12\x05thing\"\xda\x01\n\x11\x43\x61tchArrayRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05shape\x18\x02 \x03(\x03\x12\x15\n\x08var_name\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x1b\n\x05\x64type\x18\x04 \x01(\x0e\x32\x0c.thing.DTYPE\x12#\n\tframework\x18\x05 \x01(\x0e\x32\x10.thing.FRAMEWORK\x12\x0c\n\x04\x64\x61ta\x18\x06 \x01(\x0c\x12\x15\n\x08\x63hunk_id\x18\x07 \x01(\rH\x01\x88\x01\x01\x12\x12\n\nnum_chunks\x18\x08 \x01(\rB\x0b\n\t_var_nameB\x0b\n\t_chunk_id\" \n\x10\x43\x61tchByteRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x14\n\x12HealthCheckRequest\")\n\x08Response\x12\x1d\n\x06status\x18\x01 \x01(\x0e\x32\r.thing.STATUS*\x92\x01\n\x05\x44TYPE\x12\x08\n\x04INT8\x10\x00\x12\t\n\x05INT16\x10\x01\x12\t\n\x05INT32\x10\x02\x12\t\n\x05INT64\x10\x03\x12\t\n\x05UINT8\x10\x04\x12\n\n\x06UINT16\x10\x05\x12\n\n\x06UINT32\x10\x06\x12\n\n\x06UINT64\x10\x07\x12\x0b\n\x07\x46LOAT16\x10\x08\x12\x0b\n\x07\x46LOAT32\x10\t\x12\x0b\n\x07\x46LOAT64\x10\n\x12\x08\n\x04\x42OOL\x10\x0b**\n\tFRAMEWORK\x12\t\n\x05NUMPY\x10\x00\x12\t\n\x05TORCH\x10\x01\x12\x07\n\x03JAX\x10\x02*\"\n\x06STATUS\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x32\xb2\x01\n\x05Thing\x12\x37\n\nCatchArray\x12\x18.thing.CatchArrayRequest\x1a\x0f.thing.Response\x12\x35\n\tCatchByte\x12\x17.thing.CatchByteRequest\x1a\x0f.thing.Response\x12\x39\n\x0bHealthCheck\x12\x19.thing.HealthCheckRequest\x1a\x0f.thing.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'thing.thing_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DTYPE']._serialized_start=349
  _globals['_DTYPE']._serialized_end=495
  _globals['_FRAMEWORK']._serialized_start=497
  _globals['_FRAMEWORK']._serialized_end=539
  _globals['_STATUS']._serialized_start=541
  _globals['_STATUS']._serialized_end=575
  _globals['_CATCHARRAYREQUEST']._serialized_start=29
  _globals['_CATCHARRAYREQUEST']._serialized_end=247
  _globals['_CATCHBYTEREQUEST']._serialized_start=249
  _globals['_CATCHBYTEREQUEST']._serialized_end=281
  _globals['_HEALTHCHECKREQUEST']._serialized_start=283
  _globals['_HEALTHCHECKREQUEST']._serialized_end=303
  _globals['_RESPONSE']._serialized_start=305
  _globals['_RESPONSE']._serialized_end=346
  _globals['_THING']._serialized_start=578
  _globals['_THING']._serialized_end=756
# @@protoc_insertion_point(module_scope)
